version: "3.8"

services:
  postgres:
    build: .
    image: postgres:14.19-alpine3.22
    container_name: pg_database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - .docker/init:/docker-entrypoint-initdb.d # scripts para criar banco
    networks:
      - host-net

networks:
  host-net:
    driver: bridge
